version: "3.9"

services:         # tập hợp các container muốn chạy
  backend:
    build: ./backend                   # chỉ định thư mục chứa Dockerfile
    container_name: salary-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: salary-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend     # Chạy backend trước rồi mới chạy frontend
